//! Public entrypoints for the `did-stellar-registry` contract.
//!
//! Implements the `did:stellar` v0.1 method on Stellar/Soroban.
//! See `docs/did-spec/did-stellar-v0.1.md` for the normative specification.

use soroban_sdk::{
    contract, contractimpl, contractmeta, panic_with_error, Address, BytesN, Env, String,
};

use crate::errors::RegistryError;
use crate::events;
use crate::model::{
    DidKey, DidRecord, DidService, MAX_KEY_COUNT_AGREEMENT, MAX_KEY_COUNT_ASSERT,
    MAX_KEY_COUNT_AUTH, MAX_KEY_MULTIBASE_LEN, MAX_SERVICE_COUNT, MAX_SERVICE_ID_LEN,
    MAX_SERVICE_TYPE_LEN, MAX_URL_LEN, MIN_KEY_COUNT_AUTH,
};
use crate::storage;

contractmeta!(
    key = "Description",
    val = "did-stellar-registry: on-chain registry for did:stellar DIDs",
);

/// Public ABI of the registry contract.
///
/// `expected_version` is the value of `DidRecord.version` the caller observed
/// before composing the mutation. The contract rejects the call with
/// `VersionMismatch` if it does not equal the on-chain version at the time
/// of execution (optimistic concurrency).
///
/// The client struct (`DidStellarRegistryClient`) is auto-generated by
/// `#[contractimpl]` from the contract struct name.
pub trait DidStellarRegistryInterface {
    /// Register a new DID. Fails with `DidAlreadyExists` if `did_id` is taken.
    /// `initial_record.controller` MUST authorize.
    fn register(e: Env, did_id: BytesN<16>, initial_record: DidRecord);

    /// Register a new DID paid for by `sponsor`. Only `sponsor` MUST
    /// authorize; the controller does not sign and owns the DID from version
    /// 1. Fails with `SponsorIsController` if the two addresses match.
    ///
    /// The controller address is never proved here, and a wrong one yields a
    /// permanently immutable record. Callers MUST validate it off-chain; see
    /// spec §4.4.2.
    fn register_sponsored(e: Env, sponsor: Address, did_id: BytesN<16>, initial_record: DidRecord);

    /// Replace the current `DidRecord` with `next_record`. Fails with
    /// `VersionMismatch` if the on-chain version does not match
    /// `expected_version`. Fails with `DidDeactivated` if the DID is already
    /// deactivated. The current controller MUST authorize.
    fn update(e: Env, did_id: BytesN<16>, expected_version: u32, next_record: DidRecord);

    /// Transfer control of the DID to `new_controller`. Preserves all keys,
    /// services, and metadata. Bumps version. The current controller MUST
    /// authorize.
    fn transfer_controller(
        e: Env,
        did_id: BytesN<16>,
        expected_version: u32,
        new_controller: Address,
    );

    /// Permanently deactivate the DID. Empties cryptographic material;
    /// preserves controller and metadata for audit. Irreversible. The current
    /// controller MUST authorize.
    fn deactivate(e: Env, did_id: BytesN<16>, expected_version: u32);

    /// Read-only. Returns the current `DidRecord`, or `None` if no record
    /// exists for `did_id`. Does not require authorization.
    fn get(e: Env, did_id: BytesN<16>) -> Option<DidRecord>;

    // --- Contract-level admin -----------------------------------------------
    // The admin governs future contract-wide operations (none today; reserved
    // for emergency pause, parameter updates, etc.). Per-DID mutations are
    // NOT admin-gated - they remain authorized exclusively by the DID
    // controller.

    /// Propose a new contract admin. The current admin MUST authorize. The
    /// nominee must call `accept_admin` to complete the transfer; the
    /// proposal lives in temporary storage and expires automatically.
    fn propose_admin(e: Env, new_admin: Address);

    /// Accept a pending admin nomination. The proposed admin MUST authorize.
    /// Fails with `NoProposedAdmin` if there is no active proposal.
    fn accept_admin(e: Env);

    /// Read the current contract admin. No authorization required.
    fn get_admin(e: Env) -> Address;
}

#[contract]
pub struct DidStellarRegistry;

#[contractimpl]
impl DidStellarRegistry {
    /// Soroban constructor - runs exactly once at deployment time. Sets the
    /// initial admin. The deployer MUST sign as `admin`.
    pub fn __constructor(e: Env, admin: Address) {
        admin.require_auth();
        storage::set_admin(&e, &admin);
        storage::extend_instance(&e);
        events::contract_initialized(&e, &admin);
    }
}

#[contractimpl]
impl DidStellarRegistryInterface for DidStellarRegistry {
    fn register(e: Env, did_id: BytesN<16>, initial_record: DidRecord) {
        if storage::has_record(&e, &did_id) {
            panic_with_error!(&e, RegistryError::DidAlreadyExists);
        }

        // Authorization: the caller is asserting they control this address.
        initial_record.controller.require_auth();

        // Validate the payload - bounds, formats, no duplicates.
        validate_record(&e, &initial_record);

        // Override creation/update bookkeeping. Whatever the caller passed in
        // for `version`, `created_ledger`, `updated_ledger`, and `deactivated`
        // is ignored: the contract is the source of truth for these fields.
        let current_ledger = e.ledger().sequence();
        let record = DidRecord {
            controller: initial_record.controller.clone(),
            authentication: initial_record.authentication,
            assertion_method: initial_record.assertion_method,
            key_agreement: initial_record.key_agreement,
            services: initial_record.services,
            metadata_uri: initial_record.metadata_uri,
            metadata_hash: initial_record.metadata_hash,
            version: 1,
            created_ledger: current_ledger,
            updated_ledger: current_ledger,
            deactivated: false,
        };

        storage::write_record(&e, &did_id, &record);
        events::did_registered(&e, &did_id, &record.controller, record.version);
    }

    fn register_sponsored(e: Env, sponsor: Address, did_id: BytesN<16>, initial_record: DidRecord) {
        if storage::has_record(&e, &did_id) {
            panic_with_error!(&e, RegistryError::DidAlreadyExists);
        }

        // Only the sponsor signs. That is the point of this entrypoint, and
        // its risk.
        sponsor.require_auth();

        // Sponsoring yourself is `register` plus a custody window.
        if sponsor == initial_record.controller {
            panic_with_error!(&e, RegistryError::SponsorIsController);
        }

        validate_record(&e, &initial_record);

        let current_ledger = e.ledger().sequence();
        let record = DidRecord {
            controller: initial_record.controller.clone(),
            authentication: initial_record.authentication,
            assertion_method: initial_record.assertion_method,
            key_agreement: initial_record.key_agreement,
            services: initial_record.services,
            metadata_uri: initial_record.metadata_uri,
            metadata_hash: initial_record.metadata_hash,
            version: 1,
            created_ledger: current_ledger,
            updated_ledger: current_ledger,
            deactivated: false,
        };

        storage::write_record(&e, &did_id, &record);
        events::did_registered_sponsored(&e, &did_id, &sponsor, &record.controller, record.version);
    }

    fn update(e: Env, did_id: BytesN<16>, expected_version: u32, next_record: DidRecord) {
        let current = require_record(&e, &did_id);
        require_active(&e, &current);
        require_version(&e, expected_version, current.version);

        // The current controller authorizes the mutation. The controller field
        // is immutable through `update`; ownership changes must go through
        // `transfer_controller`, which emits the dedicated
        // `DidControllerTransferred` event so off-chain indexers can track
        // ownership changes reliably.
        current.controller.require_auth();

        validate_record(&e, &next_record);

        if current.version == u32::MAX {
            panic_with_error!(&e, RegistryError::VersionOverflow);
        }
        let new_version = current.version + 1;
        let updated = DidRecord {
            // Controller is pinned to the current value - next_record.controller
            // is intentionally ignored here.
            controller: current.controller.clone(),
            authentication: next_record.authentication,
            assertion_method: next_record.assertion_method,
            key_agreement: next_record.key_agreement,
            services: next_record.services,
            metadata_uri: next_record.metadata_uri,
            metadata_hash: next_record.metadata_hash,
            version: new_version,
            // `created_ledger` is immutable after registration.
            created_ledger: current.created_ledger,
            updated_ledger: e.ledger().sequence(),
            // Deactivation is one-way and only happens via `deactivate`.
            deactivated: false,
        };

        storage::write_record(&e, &did_id, &updated);
        events::did_updated(&e, &did_id, new_version);
    }

    fn transfer_controller(
        e: Env,
        did_id: BytesN<16>,
        expected_version: u32,
        new_controller: Address,
    ) {
        let current = require_record(&e, &did_id);
        require_active(&e, &current);
        require_version(&e, expected_version, current.version);
        current.controller.require_auth();

        if current.version == u32::MAX {
            panic_with_error!(&e, RegistryError::VersionOverflow);
        }
        let new_version = current.version + 1;
        let old_controller = current.controller.clone();
        let updated = DidRecord {
            controller: new_controller.clone(),
            authentication: current.authentication,
            assertion_method: current.assertion_method,
            key_agreement: current.key_agreement,
            services: current.services,
            metadata_uri: current.metadata_uri,
            metadata_hash: current.metadata_hash,
            version: new_version,
            created_ledger: current.created_ledger,
            updated_ledger: e.ledger().sequence(),
            deactivated: false,
        };

        storage::write_record(&e, &did_id, &updated);
        events::did_controller_transferred(
            &e,
            &did_id,
            &old_controller,
            &new_controller,
            new_version,
        );
    }

    fn deactivate(e: Env, did_id: BytesN<16>, expected_version: u32) {
        let current = require_record(&e, &did_id);
        require_active(&e, &current);
        require_version(&e, expected_version, current.version);
        current.controller.require_auth();

        if current.version == u32::MAX {
            panic_with_error!(&e, RegistryError::VersionOverflow);
        }
        let new_version = current.version + 1;
        // Tombstone state: empty key sets, preserve controller + metadata for
        // audit.
        let tombstone = DidRecord {
            controller: current.controller,
            authentication: soroban_sdk::Vec::new(&e),
            assertion_method: soroban_sdk::Vec::new(&e),
            key_agreement: soroban_sdk::Vec::new(&e),
            services: soroban_sdk::Vec::new(&e),
            metadata_uri: current.metadata_uri,
            metadata_hash: current.metadata_hash,
            version: new_version,
            created_ledger: current.created_ledger,
            updated_ledger: e.ledger().sequence(),
            deactivated: true,
        };

        storage::write_record(&e, &did_id, &tombstone);
        events::did_deactivated(&e, &did_id, new_version);
    }

    fn get(e: Env, did_id: BytesN<16>) -> Option<DidRecord> {
        storage::read_record(&e, &did_id)
    }

    fn propose_admin(e: Env, new_admin: Address) {
        let admin = storage::get_admin(&e);
        admin.require_auth();
        storage::set_proposed_admin(&e, &new_admin);
        storage::extend_instance(&e);
    }

    fn accept_admin(e: Env) {
        match storage::get_proposed_admin(&e) {
            Some(proposed) => {
                proposed.require_auth();
                let old_admin = storage::get_admin(&e);
                storage::set_admin(&e, &proposed);
                storage::remove_proposed_admin(&e);
                storage::extend_instance(&e);
                events::admin_transferred(&e, &old_admin, &proposed);
            }
            None => panic_with_error!(&e, RegistryError::NoProposedAdmin),
        }
    }

    fn get_admin(e: Env) -> Address {
        storage::get_admin(&e)
    }
}

// --- Helpers (private) ---

fn require_record(e: &Env, did_id: &BytesN<16>) -> DidRecord {
    match storage::read_record(e, did_id) {
        Some(r) => r,
        None => panic_with_error!(e, RegistryError::DidNotFound),
    }
}

fn require_active(e: &Env, record: &DidRecord) {
    if record.deactivated {
        panic_with_error!(e, RegistryError::DidDeactivated);
    }
}

fn require_version(e: &Env, expected: u32, current: u32) {
    if expected != current {
        panic_with_error!(e, RegistryError::VersionMismatch);
    }
}

/// Full record validation. Enforces every bound declared in `model.rs`.
/// Called from `register` and `update`. Does NOT inspect or modify the
/// version/ledger/deactivated bookkeeping fields - those are owned by the
/// contract.
fn validate_record(e: &Env, record: &DidRecord) {
    // --- Key counts ---
    let auth_len = record.authentication.len();
    if !(MIN_KEY_COUNT_AUTH..=MAX_KEY_COUNT_AUTH).contains(&auth_len) {
        panic_with_error!(e, RegistryError::InvalidAuthKeyCount);
    }
    if record.assertion_method.len() > MAX_KEY_COUNT_ASSERT {
        panic_with_error!(e, RegistryError::InvalidAssertionKeyCount);
    }
    if record.key_agreement.len() > MAX_KEY_COUNT_AGREEMENT {
        panic_with_error!(e, RegistryError::InvalidKeyAgreementCount);
    }
    if record.services.len() > MAX_SERVICE_COUNT {
        panic_with_error!(e, RegistryError::InvalidServiceCount);
    }

    // --- Per-key validation + intra-relationship duplicate detection ---
    validate_keys_no_duplicates(e, &record.authentication);
    validate_keys_no_duplicates(e, &record.assertion_method);
    validate_keys_no_duplicates(e, &record.key_agreement);

    // --- Services ---
    // Each service is validated individually, and `id_suffix` must be unique
    // across all services - duplicates would resolve to the same
    // `{did}#service-{id_suffix}` fragment, making the DID Document ambiguous.
    // Pairwise comparison is bounded because `services.len() <= MAX_SERVICE_COUNT` (3).
    for i in 0..record.services.len() {
        let s: DidService = record.services.get_unchecked(i);
        validate_service(e, &s);
        for j in (i + 1)..record.services.len() {
            let other: DidService = record.services.get_unchecked(j);
            if s.id_suffix == other.id_suffix {
                panic_with_error!(e, RegistryError::DuplicateServiceId);
            }
        }
    }

    // --- Optional metadata URI ---
    if let Some(uri) = &record.metadata_uri {
        if !is_valid_https_url(uri) {
            panic_with_error!(e, RegistryError::MetadataUriInvalid);
        }
    }

    // --- Metadata consistency ---
    // A hash without a URI is orphaned: there is no referent to verify
    // against. Reject this combination to prevent incoherent records.
    if record.metadata_hash.is_some() && record.metadata_uri.is_none() {
        panic_with_error!(e, RegistryError::MetadataInconsistent);
    }
}

fn validate_keys_no_duplicates(e: &Env, keys: &soroban_sdk::Vec<DidKey>) {
    let n = keys.len();
    for i in 0..n {
        let k: DidKey = keys.get_unchecked(i);
        validate_key(e, &k);
        // Compare against later entries - pairwise comparison is bounded
        // because `n <= 3`.
        for j in (i + 1)..n {
            let other: DidKey = keys.get_unchecked(j);
            if k.public_key_multibase == other.public_key_multibase {
                panic_with_error!(e, RegistryError::DuplicateKey);
            }
        }
    }
}

fn validate_key(e: &Env, key: &DidKey) {
    let len = key.public_key_multibase.len();
    if len == 0 {
        panic_with_error!(e, RegistryError::KeyEmpty);
    }
    if len > MAX_KEY_MULTIBASE_LEN {
        panic_with_error!(e, RegistryError::KeyTooLong);
    }
}

fn validate_service(e: &Env, s: &DidService) {
    if s.id_suffix.len() > MAX_SERVICE_ID_LEN {
        panic_with_error!(e, RegistryError::ServiceIdTooLong);
    }
    if s.id_suffix.is_empty() {
        panic_with_error!(e, RegistryError::ServiceIdInvalidFormat);
    }
    if !is_valid_id_suffix(&s.id_suffix) {
        panic_with_error!(e, RegistryError::ServiceIdInvalidFormat);
    }
    if s.service_type.is_empty() {
        panic_with_error!(e, RegistryError::ServiceTypeEmpty);
    }
    if s.service_type.len() > MAX_SERVICE_TYPE_LEN {
        panic_with_error!(e, RegistryError::ServiceTypeTooLong);
    }
    if !is_valid_https_url(&s.service_endpoint) {
        panic_with_error!(e, RegistryError::ServiceEndpointInvalid);
    }
}

/// `^[a-z0-9][a-z0-9-]*[a-z0-9]$` or a single `[a-z0-9]` char.
/// Lowercase ASCII letters, digits, and interior hyphens only.
/// Leading and trailing hyphens (e.g. `-foo`, `foo-`) are rejected.
fn is_valid_id_suffix(s: &String) -> bool {
    let bytes = s.to_bytes();
    let n = bytes.len();
    if n == 0 {
        return false;
    }
    // Leading or trailing hyphens are not valid slug identifiers.
    if bytes.get_unchecked(0) == b'-' || bytes.get_unchecked(n - 1) == b'-' {
        return false;
    }
    for i in 0..n {
        let b = bytes.get_unchecked(i);
        let ok = b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-';
        if !ok {
            return false;
        }
    }
    true
}

/// Accepts only URLs that begin with the literal prefix `https://` and are
/// no longer than `MAX_URL_LEN`. Does not parse or validate the host.
fn is_valid_https_url(s: &String) -> bool {
    let len = s.len();
    if len <= 8 || len > MAX_URL_LEN {
        return false;
    }
    let bytes = s.to_bytes();
    let prefix = b"https://";
    for i in 0..8u32 {
        if bytes.get_unchecked(i) != prefix[i as usize] {
            return false;
        }
    }
    true
}
